"""GaussianWrapping GUI - conda-free lightweight installer for Windows.

This installer keeps the heavy CUDA build path, but skips the CGAL-based
tetra_triangulation extension. Mesh extraction uses GaussianWrapping's scipy
Delaunay fallback instead. It is slower than the CGAL path, but avoids
Miniconda/conda-forge entirely.
"""
import argparse
import json
import os
import sys

import install as full


PROFILE = "venv-scipy"


def ensure_python_version():
    if sys.version_info[:2] != (3, 11):
        full.die(
            "Python 3.11 is required for this lightweight installer.\n"
            f"Current interpreter: {sys.version.split()[0]}\n"
            "Install Python 3.11, then re-run install_venv.bat."
        )


def env_root_from_python(py):
    scripts = os.path.dirname(os.path.abspath(py))
    if os.path.basename(scripts).lower() == "scripts":
        return os.path.dirname(scripts)
    return scripts


def venv_python(venv_dir):
    return os.path.join(os.path.abspath(venv_dir), "Scripts", "python.exe")


def ensure_venv(venv_dir):
    py = venv_python(venv_dir)
    if os.path.isfile(py):
        full.log(f"[SKIP] venv already exists: {os.path.abspath(venv_dir)}")
        return py
    full.log(f"[STEP] creating venv: {os.path.abspath(venv_dir)}")
    full.run([sys.executable, "-m", "venv", os.path.abspath(venv_dir)])
    return py


def ensure_base_tools(py):
    full.log("[STEP] upgrading pip/setuptools/wheel")
    full.run([py, "-m", "pip", "install", "--upgrade", "pip", "setuptools", "wheel"])


def build_env_vars(cuda_home, arch, env_py):
    env = os.environ.copy()
    prefix = env_root_from_python(env_py)
    path_parts = [
        os.path.join(cuda_home, "bin"),
        os.path.join(prefix, "Scripts"),
    ]
    env.update({
        "CUDA_HOME": cuda_home,
        "CUDA_PATH": cuda_home,
        "TORCH_CUDA_ARCH_LIST": arch,
        "DISTUTILS_USE_SDK": "1",
        "VSLANG": "1033",
        "NVCC_APPEND_FLAGS": "-DUSE_CUDA",
        "PYTHONUTF8": "1",
        "PATH": ";".join(path_parts + [env["PATH"]]),
    })
    return env


def ensure_scipy(py):
    if full.module_ok(py, "scipy"):
        full.log("[SKIP] scipy already installed")
        return
    full.log("[STEP] installing scipy for Delaunay fallback")
    full.run([py, "-m", "pip", "install", "scipy"])


def write_config(py, cuda_home, vcvars, arch):
    env_root = env_root_from_python(py)
    cfg = {
        "env_python": py,
        "env_root": env_root,
        "gw_repo": full.GW_DIR,
        "cuda_home": cuda_home,
        "vcvars": vcvars,
        "arch": arch,
        "install_profile": PROFILE,
        "delaunay_method": "scipy",
        "tetra_triangulation": "skipped",
    }
    with open(full.CONFIG, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)
    full.log(f"[OK] wrote {full.CONFIG}")

    env_bat = os.path.join(full.HERE, "launch_env.bat")
    with open(env_bat, "w", encoding="ascii", newline="\r\n") as f:
        f.write("@echo off\n"
                "REM Generated by install_venv.py - do not edit (re-run install_venv.bat instead).\n"
                f'set "PY={py}"\n'
                f'set "GWGUI_ENV_ROOT={env_root}"\n'
                f'set "VCVARS={vcvars}"\n'
                f'set "CUDA_HOME={cuda_home}"\n'
                f'set "TORCH_CUDA_ARCH_LIST={arch}"\n'
                'set "GWGUI_INSTALL_PROFILE=venv-scipy"\n'
                'set "GWGUI_DELAUNAY_METHOD=scipy"\n')
    full.log(f"[OK] wrote {env_bat}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--venv", default=os.path.join(full.HERE, ".venv"),
                    help="venv directory to create/use")
    ap.add_argument("--arch", default=None, help="GPU compute capability, e.g. 12.0")
    ap.add_argument("--cuda", default=None, help="CUDA 12.8 install dir")
    ap.add_argument("--vcvars", default=None, help="path to vcvars64.bat")
    args = ap.parse_args()

    ensure_python_version()
    full.log("=" * 64)
    full.log("GaussianWrapping GUI lightweight installer (venv + scipy fallback)")
    full.log("=" * 64)
    arch = full.detect_gpu_arch(args.arch)
    cuda_home = full.detect_cuda(args.cuda)
    vcvars = full.detect_vcvars(args.vcvars)

    py = ensure_venv(args.venv)
    ensure_base_tools(py)
    full.ensure_torch(py)
    full.ensure_fork()
    full.patch_nvdiffrast()
    full.ensure_requirements(py)
    ensure_scipy(py)
    env = build_env_vars(cuda_home, arch, py)
    full.ensure_extensions(py, vcvars, env)
    full.log("[SKIP] tetra_triangulation/CGAL (using --delaunay_method scipy)")
    write_config(py, cuda_home, vcvars, arch)

    full.log("[STEP] smoke test")
    rc = full.run_in_vcvars(
        vcvars,
        [py, os.path.join(full.HERE, "smoke_test.py"), "--allow-missing-tetranerf"],
        env,
        cwd=full.HERE,
    )
    if rc != 0:
        full.die("smoke test failed - see the list above for the failing component")
    full.log("")
    full.log("=" * 64)
    full.log("LIGHTWEIGHT INSTALL COMPLETE. Start the app with launch_gui.bat")
    full.log("=" * 64)


if __name__ == "__main__":
    main()
